spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/flea_campus
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 1000MB
  application:
    name: fc-core
  web:
    resources:
      static-locations: file:file/, classpath:/static

logging:
  level:
    com:
      gyh:
        fleacampus:
          core:
            mapper: DEBUG

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.gyh.fleacampus.core.mapper

knife4j:
  enable: true
  documents:
    - group: 1.0版本
      name: 登录
      # 某一个文件夹下所有的.md文件
      locations: classpath:static/*

server:
  port: 81
  http2:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    groups:
      enabled: true
  show-actuator: true

fileUploadPath: file/
