spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/flea_campus
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB

logging:
  level:
    com:
      gyh:
        fleacampus:
          mapper: DEBUG
  file:
    path: core-logger
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 60
  pattern:
    file: "${FILE_LOG_PATTERN:%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"


mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.gyh.fleacampus.core.mapper

knife4j:
  enable: true
  documents:
    - group: 1.0版本
      name: 登录
      # 某一个文件夹下所有的.md文件
      locations: classpath:static/*

server:
  port: 81
  http2:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    groups:
      enabled: true
  show-actuator: true

fileUploadPath: file/