spring:
  r2dbc:
    username: postgres
    password: admin
    url: r2dbc:postgres://localhost:5432/flea_campus
    pool:
      enabled: true
  web:
    resources:
      static-locations: file:file/, classpath:/static
  redis:
    host: localhost
    port: 6379
    timeout: 5000

logging:
  level:
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.r2dbc: DEBUG
  file:
    path: socket-logger
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 60
  pattern:
    file: "${FILE_LOG_PATTERN:%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"


server:
  port: 82

